---
- name: Deploy ethereum - execution and consensus only - default clients (geth & lighthouse)
  hosts: 127.0.0.1
  connection: local
  become: true


  vars:
    deploy_execution: true
    deploy_consensus: true
    deploy_validator: false
  
    network: ethereum
    suggested_fee_recipient: "0xa10214731A6D9eC03d36d1437796D1cEe6a061f7"

    enable_firewall: false

  roles:
    - role: geerlingguy.docker
      vars:
        docker_package_state: present
        docker_install_compose_plugin: true
        
    - role: slingnode.ethereum
