---
- name: Deploy ethereum - execution and consensus only - default clients (geth & lighthouse)
  hosts: 127.0.0.1
  connection: local
  become: true


  vars:
    deploy_execution: true
    deploy_consensus: true
    deploy_validator: false
  
    network: mainnet
    suggested_fee_recipient: "0xa10214731A6D9eC03d36d1437796D1cEe6a061f7"

    enable_firewall: false
    host_ip_address_to_bind_to: 0.0.0.0
    execution_client_json_rpc_websocket_enabled: true
    expose_execution_client_authrpc_port_to_host: true
    expose_execution_client_json_rpc_port_to_host: true
    expose_execution_client_json_rpc_websocket_port_to_host: true
    expose_execution_client_metrics_port_to_host: true
    expose_consensus_client_http_port_to_host: true
    expose_consensus_client_metrics_port_to_host: true

    geth_http_api: web3,eth,net,txpool

    monitoring_server: false
    install_monitoring_agents: true
    monitoring_server_host: "10.10.194.255"
    single_server_deployment: false

    ethereum_metrics_exporter_docker_image: ethpandaops/ethereum-metrics-exporter:0.23.0

  roles:
    - role: geerlingguy.docker
      vars:
        docker_package_state: present
        docker_install_compose_plugin: true
        
    - role: slingnode.ethereum
        
    - role: slingnode.ethereum_observability
